### ISSUE TITLE
make the current sort button green (check the green color used)

### ISSUE THREAD

**Issue by unclebay143** [unclebay143/nigeria-presidents#10]
when the profile card is sort by latest - the sort by latest button should have a background color of green

when the profile card is sort by old - the sort by old button should have a background color of green

**Comment by joshi-kaushal** [comment]
Can I work on this issue under hacktoberfest?

**Comment by asitsonawane** [comment]
Can you please assign this issue? I would like to work on this issue for hacktoberfest2021.

**Comment by plavani0208** [comment]
Can you please assign this issue? I would like to work on this for HacktoberFest 2021.

**Comment by unclebay143** [comment]
I guess anyone can send a PR

anyone who sent in a valid request first

**Comment by abhinaisai2002** [comment]
Can I work on this issue under hacktoberfest?

**Comment by copyNinja1219** [comment]
can i work on this issue ?

**Comment by unclebay143** [comment]
> can i work on this issue ?

Yes please

**Comment by unclebay143** [comment]
> Can I work on this issue under hacktoberfest?

Yes you can go ahead and send a pr

**Comment by yogendra-17** [comment]
can i work on this issue?
