### ISSUE TITLE
Fix the sortBy old button

### ISSUE THREAD

**Issue by unclebay143** [unclebay143/nigeria-presidents#5]
Requires a javascript function to sort the president's profile and view them from old to new presidents

**Comment by parthpanchal123** [comment]
The sorting has to be performed on the basis of "From" year field right ?

**Comment by unclebay143** [comment]
> The sorting has to be performed on the basis of "From" year field right ?

💯 you are on point 👍

**Comment by parthpanchal123** [comment]
Opened a PR [#9](https://github.com/unclebay143/nigeria-presidents/pull/9)
