### ISSUE TITLE
create view more page for the presidents profile on click

### ISSUE THREAD

**Issue by unclebay143** [unclebay143/nigeria-presidents#6]
Visitors should be able to click and preview more information about the selected president

**Comment by SaakshiShah25** [comment]
Hey @unclebay143, can you assign this issue to me?

**Comment by unclebay143** [comment]
> Hey @unclebay143, can you assign this issue to me?

sure

**Comment by Eunit99** [comment]
Hi @unclebay143, I would still like to work in this.  Kindly assign me.

Thanks

**Comment by Prashantsetia** [comment]
hi @unclebay143 , can you please assign this issue to me ? I will make sure to provide its solution in shortest possible time

**Comment by unclebay143** [comment]
> Hi @unclebay143, I would still like to work in this. Kindly assign me.
> 
> Thanks

Sure, please go ahead and send a PR

**Comment by unclebay143** [comment]
> hi @unclebay143 , can you please assign this issue to me ? I will make sure to provide its solution in shortest possible time

You can proceed to send a PR

**Comment by copyNinja1219** [comment]
I created a pr please check

**Comment by Prashantsetia** [comment]
I have also sent you PR, please check

**Comment by unclebay143** [comment]
View more page created, you can also improve it by displaying more details from the presidents object.
